#Prod Configuration

emburse:
    tokenEndpoint: "https://login.salesforce.com/services/oauth2/token"
    modified : "005Vt00000442ovIAA"


chromeriver:
    tokenEndpoint: "https://login.salesforce.com/services/oauth2/token"
