#Local Configuration


emburse:
    tokenEndpoint: "https://test.salesforce.com/services/oauth2/token"
    username: "mulesoftintegration@emburse.com.eouat"


chromeriver:
    tokenEndpoint: "https://test.salesforce.com/services/oauth2/token"
    username: "mulesoftintegration@emburse.com.uat"
    modified : "005WJ000005UQbhYAG"

