#Dev Configuration

emburse:
    tokenEndpoint: "https://test.salesforce.com/services/oauth2/token"
    modified : "005WJ000005UQbhYAG"


chromeriver:
    tokenEndpoint: "https://test.salesforce.com/services/oauth2/token"
