#Prod Configuration

emburse:
    tokenEndpoint: "https://login.salesforce.com/services/oauth2/token"
    username: "mulesoftintegration@emburse.com.eo"
    
chromeriver:
    tokenEndpoint: "https://login.salesforce.com/services/oauth2/token"
    username: "mulesoftintegration@emburse.com.cr"
    modified : "005Vt00000442ovIAA"
