#Prod Secure Configuration

#Emburse creds
emburse:
  consumerKey: ""
  consumerSecret: ""
  username: ""
  password: ""
  securityToken: ""

#Chrome River creds
chromeriver:
  consumerKey: ""
  consumerSecret: ""
  username: ""
  password: ""
  securityToken: ""