#Prod Secure Configuration

#Emburse creds
emburse:
  consumerKey: "![XdURsIQ8x3wdsQrw+lMWx/tOCgf8BHp7t6w3XFGeYUA4kpojfxyos5UIYvHXXwAqAo93K38Zd5oLMjadgqk3GWtTAnfHPnuB6EESM0VQg7TndB5PHo7fS1KZ51mJi3N7]"
  consumerSecret: "![Xubey2rmc7s3Xo+lZUwLhRxtaXRI86ZOBiG7CumvEqP6qYwL/KjZ+5G8FZc3cK4tDgxlEDd3SReAfwmk1jK82BBOBrlvVYH51aLeOkeb3PQ=]"
  username: "![wJTBuPbb6+d6NEvgFWqzZjmqhFjdz3aQ44MlCg9ncmmEJM/T+ptfxGoCXJVT7d+f]"
  password: "![Ft+c1Dm8Xx8Z86D3uJdkqQ==]"
  securityToken: "![fDnVB7stj6FjTdeONglfAjKhk9I5uTXyTPzUd5zAhlo=]"

#Chrome River creds
chromeriver:
  consumerKey: "![Zs7gzKajKG075IVe34/a+UtmSEfymaBPnUR/O0D397ydgCApWWjI9c88Xo2K0YxjaipCDhMw9uNTJ7HF1y8IfEgLhW6k7OMzhjcAJ8w5LSxkn7CX5tAtUgNM8QdkiUwB]"
  consumerSecret: "![s3HEtouRveHPIvY7F1dYJdrSaXZoBevNr0uaH40T06OgwrOWCksWYWsFKG8obacR1daSDgIWm28Mos2AT48boioFdG9ac89RGcnAvEvERgY=]"
  username: "![wJTBuPbb6+d6NEvgFWqzZjmqhFjdz3aQ44MlCg9ncmkhaI9VOgNUVPz936SF5N95]"
  password: "![KX0Y5zBWuAQdf4dyf6+oCg==]"
  securityToken: "![V75OVAKJDKe5TmYAQe0FxjoVtS2efu+GMJE2Uh4dMCY=]"