#Prod Secure Configuration

#Emburse creds
emburse:
  consumerKey: "![kycCrnTiu5O39qzMJDRNfhEdHalxiWxYbMF5OCrhu17Q9PPsNej5NiiE/JRd0/I/3ErMeGZDzCbfCjygAVZ61r+E6Kh/CVSQriq1Vasq1B2FL8AZGBwE4Uh5kJBIysMy]"
  consumerSecret: "![/qnS54yaha577tKBljOuuIt4LdcewQmUggVS0De7W13TBJDOSnmWSh9Ic/J8AWSgTWBMzl2Z9BHfm+ilrzYTDLObDPe6IljBC5ynzav1cdQ=]"
  password: "![oQzZuNNdbthiY0dJSL8eMg==]"
  securityToken: "![BfNK0rnkUYXpanlqOCfx4geCC27oHNGtrCqKRvWN/xs=]"

#Chrome River creds
chromeriver:
    consumerKey: "![nqnU166i8oeysN/bFgkQV3cPTQmcy+8XVVzqNrY9ceGYTmFBfSXRornDY5IEqkOg6wGxQGz62z/amOPQlu6FZrYxI2eE7/wExEN3LH3OV/Hx3rqCXOj2jx/4ZtyLTDY5]"
    consumerSecret: "![BPhOIE+dpQLfrMFIHlWdkFNcGfwIqTKU3PSuQwS+PYIByGDfYQJ2UXV44SYR2SYkdNJZH+kUGrVITgSdbvvRPWyYNN2hoxTp7HcTuKLWwkU=]"
    password: "![6hstrIsXYS6BMJB/6cDZYA==]"
    securityToken: "![CbudHaPWu/CNzKGb1FNqlXtObgvhFGS2UNj6brViORQ=]"